name: "Test AWFY benchmarks"
on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        smalltalk: [ Squeak64-6.0, Squeak64-trunk ]
    name: ${{ matrix.smalltalk }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - run: smalltalkci -s ${{ matrix.smalltalk }}
        timeout-minutes: 15
