name: Test TruffleSqueak

on:
  push:
    branches-ignore:
      - 'experiements/**'
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - gu-catalog.properties
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - gu-catalog.properties

jobs:
  style_and_build_config:
    name: Code Style + Build Config
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    steps:
    - name: Clone TruffleSqueak repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Set up dependencies
      run: |
        # Download Eclipse SDK
        eclipse_tar_path="${RUNNER_TEMP}/eclipse.tar.gz"
        wget --no-verbose https://archive.eclipse.org/eclipse/downloads/drops4/R-4.14-201912100610/eclipse-SDK-4.14-linux-gtk-x86_64.tar.gz -O ${eclipse_tar_path}
        tar -xzf ${eclipse_tar_path} -C ${RUNNER_TEMP}
        echo "ECLIPSE_EXE=${RUNNER_TEMP}/eclipse/eclipse" >> "${GITHUB_ENV}" # required by mx
        echo "JDT=builtin" >> "${GITHUB_ENV}" # required by mx
        # Set up mx, oracle/graal, and LabsJDK11
        mx.trufflesqueak/utils.sh "set-up-mx && shallow-clone-graal && set-up-labsjdk labsjdk-ce-11 ~/"
        # Set up style dependencies
        sudo apt update && sudo apt install python3-pip python-setuptools
        cat ../graal/common.json |
          jq -r '.deps.common.packages | to_entries[] | select(.key | startswith("pip:")) | (.key | split(":")[1]) + .value' |
          xargs sudo pip install
    - name: Check style and perform full build
      run: mx gate --strict-mode --tags style,fullbuild

  builds:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-20.04-aarch64, macos-11, windows-2019]
        java: [11, 17]
    env:
      RUN_TESTS: "${{ matrix.os == 'ubuntu-20.04' || matrix.java == 17 }}"
      RUN_WITH_COVERAGE: "${{ matrix.os == 'ubuntu-20.04' && matrix.java == 17 }}"
      TRUFFLESQUEAK_EXEC: "${{ matrix.os == 'windows-2019' && 'trufflesqueak.cmd' || 'trufflesqueak' }}"
      TS_INFIX: "${{ matrix.java == 11 && '_SVM' || '' }}"
      MX_ENV: "${{ matrix.java == 11 && 'trufflesqueak-svm' || 'trufflesqueak-jvm' }}"
      VERBOSE_GRAALVM_LAUNCHERS: true
    name: ${{ matrix.os }} + JDK${{ matrix.java }}
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    steps:
    - name: Clone TruffleSqueak repository
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Set up dependencies
      shell: bash
      run: mx.trufflesqueak/utils.sh set-up-dependencies java${{ matrix.java }}
    - name: Build TruffleSqueak component
      run: mx.trufflesqueak/utils.sh build-component ${{ env.MX_ENV }} ${{ matrix.java }} ${{ env.INSTALLABLE_TARGET }}
      if: ${{ matrix.os != 'windows-2019' }}
    - name: Configure pagefile # this reduces OOM kills on Windows
      uses: al-cheb/configure-pagefile-action@v1.2
      with:
        minimum-size: 8GB
        disk-root: "C:"
      if: ${{ matrix.os == 'windows-2019' }}
    - name: Build TruffleSqueak component via cmd.exe
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        call mx --env ${{ env.MX_ENV }} --no-download-progress build --dependencies SMALLTALK_INSTALLABLE${{ env.TS_INFIX }}_JAVA${{ matrix.java }},GRAALVM_TRUFFLESQUEAK${{ env.TS_INFIX }}_JAVA${{ matrix.java }}
        call mx --env ${{ env.MX_ENV }} graalvm-home > graalvm-home-with-forward-slashes.txt
        set /p GRAALVM_HOME=<graalvm-home-with-forward-slashes.txt
        setlocal enabledelayedexpansion
        set "GRAALVM_HOME=%GRAALVM_HOME:/=\%"
        echo %GRAALVM_HOME%\bin>>%GITHUB_PATH%
        echo GRAALVM_HOME=%GRAALVM_HOME%>>%GITHUB_ENV%
        echo [%GRAALVM_HOME% set as $GRAALVM_HOME]
        call mx --env ${{ env.MX_ENV }} paths SMALLTALK_INSTALLABLE${{ env.TS_INFIX }}_JAVA${{ matrix.java }} > installable-path-with-forward-slashes.txt
        set /p INSTALLABLE_PATH=<installable-path-with-forward-slashes.txt
        setlocal enabledelayedexpansion
        set "INSTALLABLE_PATH=%INSTALLABLE_PATH:/=\%"
        copy %INSTALLABLE_PATH% ${{ env.INSTALLABLE_TARGET }}
      if: ${{ matrix.os == 'windows-2019' }}
    - name: Run SystemReporter on TruffleSqueak in JVM mode
      shell: bash
      run: ${{ env.TRUFFLESQUEAK_EXEC }} --jvm --code "SystemReporter new reportText asString" images/test-64bit.image
    - name: Run SystemReporter on TruffleSqueak in native mode
      shell: bash
      run: ${{ env.TRUFFLESQUEAK_EXEC }} --native --code "SystemReporter new reportText asString" images/test-64bit.image
      if: ${{ matrix.java == 11 }}
    - name: Upload TruffleSqueak component
      shell: bash
      run: mx.trufflesqueak/utils.sh deploy-asset ${{ env.INSTALLABLE_TARGET }} ${{ secrets.GITHUB_TOKEN }}
    - name: Run Cuis-Smalltalk tests on TruffleSqueak in native mode
      run: |
        mx.trufflesqueak/utils.sh download-cuis-test-image
        trufflesqueak --native --headless --experimental-options --smalltalk.resource-summary=true --engine.CompilationFailureAction=ExitVM --engine.TreatPerformanceWarningsAsErrors=all --engine.CompilationStatistics images/Cuis6.0-????.image -s src/de.hpi.swa.trufflesqueak.test/src/de/hpi/swa/trufflesqueak/test/runCuisTests.st
      if: ${{ matrix.os == 'macos-11' && matrix.java == 11 }}
    - name: Clone Graal.js repository
      shell: bash
      run: mx.trufflesqueak/utils.sh shallow-clone-graaljs
      if: ${{ env.RUN_TESTS == 'true' }}
    - name: Run gate with Graal compiler and Graal.js
      run: mx --disable-polyglot --dy /compiler,/graal-js gate -j -n --strict-mode --tags build,test
      if: ${{ env.RUN_TESTS == 'true' && matrix.os != 'windows-2019' && env.RUN_WITH_COVERAGE != 'true' }}
    - name: Run gate with Graal.js and code coverage # do not use Graal compiler with JaCoCo code coverage
      run: mx --disable-polyglot --dy /graal-js gate -j -n --strict-mode --tags build,test --jacocout coverage
      if: ${{ env.RUN_TESTS == 'true' && matrix.os != 'windows-2019' && env.RUN_WITH_COVERAGE == 'true' }}
    - name: Run gate with Graal compiler and Graal.js via cmd.exe
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        mx --disable-polyglot --dy /compiler,/graal-js gate -j -n --strict-mode --tags build,test
      if: ${{ env.RUN_TESTS == 'true' && matrix.os == 'windows-2019' }}
    - name: Report code coverage
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: |
        bash <(curl -s https://codecov.io/bash)
        bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r jacoco.xml
      if: ${{ env.RUN_WITH_COVERAGE == 'true' && job.status == 'success' }}
    - name: Zip Graal compiler dumps
      shell: bash
      run: "[[ -d graal_dumps ]] && zip -r graal_dumps.zip graal_dumps || true"
      if: ${{ env.RUN_TESTS == 'true' }}
    - name: Upload Graal compiler dumps
      uses: actions/upload-artifact@v2
      with:
        name: graal_dumps
        path: graal_dumps.zip
        if-no-files-found: ignore
        retention-days: 5
      if: ${{ env.RUN_TESTS == 'true' }}
