name: Test TruffleSqueak

on:
  push:
    branches-ignore:
      - 'experiements/**'
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  style_and_build_config:
    name: Code Style + Build Config
    timeout-minutes: 15
    runs-on: ubuntu-18.04
    steps:
    - name: Clone TruffleSqueak repository
      uses: actions/checkout@v2
    - name: Set up dependencies
      run: |
        # Install pylint
        sudo apt update -qq && sudo apt install -qq python-pip python-virtualenv
        virtualenv ~/venv
        source ~/venv/bin/activate
        pip install --quiet astroid==1.1.0 pylint==1.1.0
        # Download Eclipse SDK
        eclipse_tar="ci-dep-eclipse-SDK-4.5.2-linux-gtk-x86_64.tar.gz"
        eclipse_tar_path="${HOME}/${eclipse_tar}"
        mx.trufflesqueak/utils.sh download-asset "${eclipse_tar}" 0.8.0 "${eclipse_tar_path}"
        tar -xzf ${eclipse_tar_path} -C ${HOME}
        echo "ECLIPSE_EXE=${HOME}/eclipse/eclipse" >> "${GITHUB_ENV}" # required by mx
        # Download ECJ
        mx.trufflesqueak/utils.sh download-asset "ci-dep-ecj-4.5.2.jar" 0.8.0 "${HOME}/ecj.jar"
        echo "JDT=${HOME}/ecj.jar" >> "${GITHUB_ENV}" # required by mx
        # Set up mx, oracle/graal, and LabsJDK11
        mx.trufflesqueak/utils.sh "set-up-mx && shallow-clone-graalvm-project https://github.com/oracle/graal.git && set-up-labsjdk11 ~/"
    - name: Check style and perform full build
      run: |
        source ~/venv/bin/activate
        mx gate --strict-mode --tags style,fullbuild

  amd64-builds:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [11, 17]
    env:
      BUILD_SVM: "${{ matrix.os != 'windows-latest' && matrix.java != 17 }}"
      RUN_TESTS: "${{ matrix.java == 11 }}"
      RUN_WITH_COVERAGE: "${{ matrix.os == 'ubuntu-latest' }}"
      GRAALVM_HOME_ENV: "${{ matrix.os == 'windows-latest' && 'trufflesqueak-jvm' || 'trufflesqueak-svm' }}"
      TRUFFLESQUEAK_EXEC: "${{ matrix.os == 'windows-latest' && 'trufflesqueak.cmd' || 'trufflesqueak' }}"
    name: ${{ matrix.os }} + JDK${{ matrix.java }}
    timeout-minutes: 90
    runs-on: ${{ matrix.os }}
    steps:
    - name: Clone TruffleSqueak repository
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up dependencies
      shell: bash
      run: mx.trufflesqueak/utils.sh set-up-dependencies java${{ matrix.java }}
    - name: Build TruffleSqueak JVM component
      run: mx.trufflesqueak/utils.sh build-component trufflesqueak-jvm SMALLTALK_INSTALLABLE_JAVA${{ matrix.java }} ${{ env.INSTALLABLE_JVM_TARGET }}
      if: ${{ matrix.os != 'windows-latest' }}
    - name: Build TruffleSqueak JVM component via cmd.exe
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        call mx --env trufflesqueak-jvm --no-download-progress build
        call mx --env trufflesqueak-jvm graalvm-home > graalvm-home-with-forward-slashes.txt
        set /p GRAALVM_HOME=<graalvm-home-with-forward-slashes.txt
        setlocal enabledelayedexpansion
        set "GRAALVM_HOME=%GRAALVM_HOME:/=\%"
        echo %GRAALVM_HOME%\bin>>%GITHUB_PATH%
        echo GRAALVM_HOME=%GRAALVM_HOME%>>%GITHUB_ENV%
        echo [%GRAALVM_HOME% set as $GRAALVM_HOME]
        call mx --env trufflesqueak-jvm paths SMALLTALK_INSTALLABLE_JAVA${{ matrix.java }} > installable-path-with-forward-slashes.txt
        set /p INSTALLABLE_PATH=<installable-path-with-forward-slashes.txt
        setlocal enabledelayedexpansion
        set "INSTALLABLE_PATH=%INSTALLABLE_PATH:/=\%"
        copy %INSTALLABLE_PATH% ${{ env.INSTALLABLE_JVM_TARGET }}
      if: ${{ matrix.os == 'windows-latest' }}
    - name: Build TruffleSqueak SVM component
      run: mx.trufflesqueak/utils.sh build-component trufflesqueak-svm SMALLTALK_INSTALLABLE_SVM_JAVA${{ matrix.java }} ${{ env.INSTALLABLE_SVM_TARGET }}
      if: ${{ env.BUILD_SVM == 'true' }}
    - name: Run SystemReporter on GraalVM
      shell: bash
      run: ${{ env.TRUFFLESQUEAK_EXEC }} --jvm --code "SystemReporter new reportText asString"
    - name: Run SystemReporter on SubstrateVM
      shell: bash
      run: ${{ env.TRUFFLESQUEAK_EXEC }} --native --code "SystemReporter new reportText asString" images/test-64bit.image
      if: ${{ env.BUILD_SVM == 'true' }}
    - name: Upload TruffleSqueak JVM component
      shell: bash
      run: mx.trufflesqueak/utils.sh deploy-asset ${{ env.INSTALLABLE_JVM_TARGET }} ${{ secrets.GITHUB_TOKEN }}
    - name: Upload TruffleSqueak SVM component
      shell: bash
      run: mx.trufflesqueak/utils.sh deploy-asset ${{ env.INSTALLABLE_SVM_TARGET }} ${{ secrets.GITHUB_TOKEN }}
      if: ${{ env.BUILD_SVM == 'true' }}
    - name: Run gate with Graal compiler and Graal.js
      run: mx --disable-polyglot --dy /compiler,/graal-js gate -j -n --strict-mode --tags build,test
      if: ${{ env.RUN_TESTS == 'true' && matrix.os != 'windows-latest' && env.RUN_WITH_COVERAGE != 'true' }}
    - name: Run gate with Graal compiler, Graal.js, and code coverage
      run: mx --disable-polyglot --dy /compiler,/graal-js gate -j -n --strict-mode --tags build,test --jacocout coverage
      if: ${{ env.RUN_TESTS == 'true' && matrix.os != 'windows-latest' && env.RUN_WITH_COVERAGE == 'true' }}
    - name: Run gate with Graal compiler and Graal.js via cmd.exe
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        mx --disable-polyglot --dy /compiler,/graal-js gate -j -n --strict-mode --tags build,test
      if: ${{ env.RUN_TESTS == 'true' && matrix.os == 'windows-latest' }}
    - name: Report code coverage
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: |
        bash <(curl -s https://codecov.io/bash)
        bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r jacoco.xml
      if: ${{ env.RUN_TESTS == 'true' && env.RUN_WITH_COVERAGE == 'true' && job.status == 'success' }}

  aarch64-builds:
    strategy:
      fail-fast: false
      matrix:
        java: [11, 17]
    name: ubuntu-20.04/aarch64 + JDK${{ matrix.java }}
    timeout-minutes: 30
    runs-on: ubuntu-18.04
    steps:
      - name: Clone TruffleSqueak repository
        uses: actions/checkout@v2
      - name: Build and test TruffleSqueak component
        uses: uraimo/run-on-arch-action@v2.0.7
        id: build_aarch64
        with:
          arch: aarch64
          distro: ubuntu20.04
          run: |
            apt update && apt install -y build-essential curl git python unzip
            mx.trufflesqueak/utils.sh "set-up-dependencies java${{ matrix.java }} && set-up-graalvm ${{ matrix.java }}"
            source "${HOME}/all_env_vars"
            export PATH="${MX_HOME}:${GRAALVM_HOME}/bin:${PATH}"
            mx --env trufflesqueak-jvm --no-download-progress build --dependencies=SMALLTALK_INSTALLABLE_JAVA${{ matrix.java }}
            cp "$(mx --env trufflesqueak-jvm paths SMALLTALK_INSTALLABLE_JAVA${{ matrix.java }})" "${INSTALLABLE_JVM_TARGET}"
            echo ::set-output name=installable_jvm::${INSTALLABLE_JVM_TARGET}
            gu install -L ${INSTALLABLE_JVM_TARGET}
            trufflesqueak --jvm --code "SystemReporter new reportText asString"
          env: |
            GITHUB_PATH: $GITHUB_PATH
            GITHUB_ENV: $GITHUB_ENV
      - name: Upload TruffleSqueak component
        run: mx.trufflesqueak/utils.sh deploy-asset ${{ steps.build_aarch64.outputs.installable_jvm }} ${{ secrets.GITHUB_TOKEN }}
